### ISSUE TITLE
Still actively developed/maintained?

### ISSUE THREAD

**Issue by ideasman42** [PhilippeNoel1/message-links.el#21]
Is this project still maintained? If not, I'd be interested to take over maintenance.

Asking because there is a PR that I'd like to use which has not been reviewed for some time.

**Comment by Qwarctick** [comment]
Sorry, I'm really busy with work atm. I can add you as a collaborator if you want.

**Comment by ideasman42** [comment]
Thanks, accepted and applied some PR's.
