### ISSUE TITLE
Is `message-links-mode` needed?

### ISSUE THREAD

**Issue by ideasman42** [PhilippeNoel1/message-links.el#4]
This package defines a minor mode that doesn't seem to do anything.

As far as I can see users can access the functions directly and the mode isn't necessary.

**Comment by Qwarctick** [comment]
I don't know, I always thought emacs packages should come in the form of a mode. I don't mind removing it if it's actually not useful

**Comment by ideasman42** [comment]
Normally a mode is needed to setup and teardown state, perhaps others have input but unless a mode is needed, I don't see why you'd have have one.

The implication would be that the commands would not work properly unless the mode was started.
